### ISSUE TITLE
Unbound silently fails if python module is enabled

### ISSUE THREAD

**Issue by divanikus** [opnsense/tools#288]
Hi. I'm on the latest opnsense (22.1.6) and trying to enable python module for `unbound`.

I've created a `/usr/local/etc/unbound.opnsense.d/python.conf`:
```
server:
  module-config: "validator python iterator"

python:
  python-script: "/usr/local/etc/unbound.opensense.d/test.py"
```

The module is just a skeleton:
```
def init_standard(id, env):
    return True

def init(id, cfg):
    return True

def deinit(id):
    return True

def inform_super(id, qstate, superqstate, qdata):
    return True

def operate(id, event, qstate, qdata):
    return True

log_info("pythonmod: script loaded")
```

`configctl unbound check` says everything is ok:
```
[1651331826] unbound-checkconf[14923:0] info: pythonmod: script loaded
no errors in /var/unbound/unbound.conf
```

And that `unbound` service cannot start. The last entry in the log is
```
[49194:0] notice: init module 1: python
```

Am I doing something wrong?
